#Alfresco MaxVersion Policy module properties
module.id=org.alfresco.extension.maxversionpolicy
module.version=0.0.11-SNAPSHOT
module.title=Alfresco MaxVersion Policy
module.description=This module adds a policy allowing you to set the max number of versions for a versioned node
module.repo.version.min=23.1.0
